// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA4AY_yTge8pBi_zOkYS-gXwJhjhe8crA',
    appId: '1:597843232761:web:f4909e309082bbd3e0df28',
    messagingSenderId: '597843232761',
    projectId: 'my-complaint-cd751',
    authDomain: 'my-complaint-cd751.firebaseapp.com',
    databaseURL: 'https://my-complaint-cd751-default-rtdb.firebaseio.com',
    storageBucket: 'my-complaint-cd751.appspot.com',
    measurementId: 'G-N3PSD1F799',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbmYxgXOjjhIoVo-zhtfP6MqJ5sOCO1Bo',
    appId: '1:597843232761:android:b2a18ad9b555534de0df28',
    messagingSenderId: '597843232761',
    projectId: 'my-complaint-cd751',
    databaseURL: 'https://my-complaint-cd751-default-rtdb.firebaseio.com',
    storageBucket: 'my-complaint-cd751.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXj1-ogAiHR49ZhijpoM6jlMJESnW_wmA',
    appId: '1:597843232761:ios:26cd449ae3f3e086e0df28',
    messagingSenderId: '597843232761',
    projectId: 'my-complaint-cd751',
    databaseURL: 'https://my-complaint-cd751-default-rtdb.firebaseio.com',
    storageBucket: 'my-complaint-cd751.appspot.com',
    iosClientId: '597843232761-c9bp68r0c9qarjjaipftlmrab9l0oqan.apps.googleusercontent.com',
    iosBundleId: 'com.example.universityCompaint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXj1-ogAiHR49ZhijpoM6jlMJESnW_wmA',
    appId: '1:597843232761:ios:26cd449ae3f3e086e0df28',
    messagingSenderId: '597843232761',
    projectId: 'my-complaint-cd751',
    databaseURL: 'https://my-complaint-cd751-default-rtdb.firebaseio.com',
    storageBucket: 'my-complaint-cd751.appspot.com',
    iosClientId: '597843232761-c9bp68r0c9qarjjaipftlmrab9l0oqan.apps.googleusercontent.com',
    iosBundleId: 'com.example.universityCompaint',
  );
}
